<?php
if (!defined('IN_FINECMS')) exit();

/**
 * 用户权限配置信息
 */
return array (
  1 => 
  array (
    0 => 'index',
    1 => 'auth',
    2 => 'category',
    3 => 'content',
    4 => 'model',
    5 => 'user',
    6 => 'position',
    7 => 'linkage',
    8 => 'plugin',
    9 => 'attachment',
    10 => 'relatedlink',
    11 => 'block',
    12 => 'member',
    13 => 'theme',
    14 => 'html',
    15 => 'form',
    16 => 'tag',
    17 => 'ip',
  ),
  2 => 
  array (
    0 => 'index-index',
    1 => 'index-config',
    2 => 'index-cache',
    3 => 'index-log',
    4 => 'index-clearlog',
    5 => 'index-updatemap',
    6 => 'auth-index',
    7 => 'auth-add',
    8 => 'auth-edit',
    9 => 'auth-del',
    10 => 'auth-set',
    11 => 'auth-cache',
    12 => 'user-index',
    13 => 'user-add',
    14 => 'user-edit',
    15 => 'user-del',
    16 => 'model-index',
    17 => 'model-add',
    18 => 'model-edit',
    19 => 'model-del',
    20 => 'model-fields',
    21 => 'model-addfield',
    22 => 'model-editfield',
    23 => 'model-delfield',
    24 => 'model-disable',
    25 => 'model-cache',
    26 => 'category-index',
    27 => 'category-add',
    28 => 'category-edit',
    29 => 'category-del',
    30 => 'category-html',
    31 => 'category-cache',
    32 => 'content-index',
    33 => 'content-add',
    34 => 'content-edit',
    35 => 'content-del',
    36 => 'content-html',
    37 => 'content-updateurl',
    38 => 'position-index',
    39 => 'position-add',
    40 => 'position-edit',
    41 => 'position-del',
    42 => 'position-list',
    43 => 'position-adddata',
    44 => 'position-editdata',
    45 => 'position-deldata',
    46 => 'position-cache',
    47 => 'html-index',
    48 => 'html-init',
    49 => 'html-category',
    50 => 'html-content',
    51 => 'html-clear',
    52 => 'plugin-index',
    53 => 'plugin-set',
    54 => 'plugin-disable',
    55 => 'plugin-del',
    56 => 'plugin-add',
    57 => 'attachment-index',
    58 => 'attachment-del',
    59 => 'attachment-file',
    60 => 'attachment-image',
    61 => 'attachment-files',
    62 => 'relatedlink-index',
    63 => 'relatedlink-add',
    64 => 'relatedlink-edit',
    65 => 'relatedlink-del',
    66 => 'relatedlink-import',
  ),
  3 => 
  array (
    0 => 'index-config',
    1 => 'auth-add',
    2 => 'auth-edit',
    3 => 'auth-set',
    4 => 'form-list',
  ),
);